graph TD
    matplotlib --> packaging
    matplotlib --> pyparsing
    matplotlib --> contourpy
    matplotlib --> cycler
    matplotlib --> pillow
    matplotlib --> kiwisolver
    matplotlib --> pybind11!
    matplotlib --> setuptools_scm
    matplotlib --> numpy
    matplotlib --> fonttools
    matplotlib --> python-dateutil
    matplotlib --> setuptools
    matplotlib --> meson-python